FROM golang:latest as builder

WORKDIR /usr/src/app

COPY /go.mod ./
RUN go mod download -x
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /app

FROM scratch
COPY --from=builder /app /app

ENTRYPOINT ["/app"]